name: orbitapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  toast: ^0.3.0
  permission_handler: ^9.0.2
  path_provider: ^2.0.7
  fluttertoast: ^8.0.9
  fullscreen: ^1.0.3
  http: ^0.13.4
  email_validator: ^2.1.2
  salomon_bottom_bar: ^3.3.1
  provider: ^6.0.0
  csc_picker: ^0.2.6
  dropdown_search: ^2.0.0
  qr_flutter: ^4.0.0
  flutter_sliding_up_panel: ^2.0.1
  animated_splash: ^1.0.0
  loading_animation_widget: ^1.1.0+5
  qr_code_scanner: ^0.7.0
  package_info: ^2.0.2
  device_info: ^2.0.3
  dropdown_button2: ^1.2.2
  fbroadcast: ^2.0.0
  flutter_svg: ^1.0.3
  js: ^0.6.2
  lottie: ^1.1.0
  flutter_chat_ui: ^0.6.5
  accordion: ^2.3.0
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  animated_theme_switcher: ^1.0.5
  file_picker: ^4.4.0
  otp_text_field: ^1.1.3
  pin_input_text_field: ^4.2.0
  fl_chart: ^0.55.2
  passcode_screen: ^2.0.1
  flutter_bloc: ^8.1.1
  animate_do: ^3.0.2
  change_app_package_name: ^1.1.0
  overlay_support: ^1.2.1
  flutter_local_notifications: ^9.5.0
  sizer: ^2.0.15
  firebase_core: ^1.9.0
  firebase_database: ^8.2.0
  firebase_messaging: ^11.1.0
  firebase_storage: ^9.0.0
  google_sign_in: ^5.2.1
  flutter_countdown_timer: ^4.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_notification_listener: ^1.3.2
  pattern_formatter: ^2.0.0
  animations: ^2.0.2
  responsive_flutter: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  hive: ^2.0.5

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Variable.ttf
    - family: SatoshiMedium
      fonts:
        - asset: assets/fonts/Satoshi-Medium.otf
    - family: SatoshiBold
      fonts:
        - asset: assets/fonts/Satoshi-Bold.otf
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Medium.otf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
    - family: RubikRegular
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: RubikMedium
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
